### PR TITLE
Try using STARTTLS without needing to try authentication(user/pass) to protect the actual email communication/content from eavesdropping.

### PR DESCRIPTION
**Pull request by PiBa-NL**
Try using STARTTLS without needing to try authentication(user/pass) to protect the actual email communication/content from eavesdropping.

### CODE REVIEW

**Comment by jparise** [comment]
Can you provide a little more context on this change? If this is a security improvement over the existing implementation, why should it be enabled by an option instead of becoming the default behavior?

**Comment by ichiken60** [comment]
If the recipient's mail server supports STARTTLS, I think this change, which will be more secure communication, is very useful, but why is it not implemented?

**Comment by Schengawegga** [comment]
Oh sorry. I put my pull request before i´ve seen this one. Why is this functionality not implemented yet? For my reason, i am using a smarthost wich authenticates the client via ip address whitelisting. So no credentials needed. But without these pull resuqest, there is no possiblitiy to start a STARTTLS encrpyted connection to the smarthost without sending credentials. Otherwise only a unectrypted connection to the smarthost is possible. To improve the security for this connection, the pull request is very useful.

**Review by jparise — COMMENTED** [review]
I like the version proposed in #64 because it makes the `STARTTLS` operation available to callers without changing any internal behavior.

... but there are some benefits to adding the "requires" flag, as you propose here.

**Comment by jparise** [comment]
Closing this in favor of the similar solution proposed in #64.

**Pull request closed without merging**
