### PR TITLE
Adding file_exists for "Auth/SASL.php"

### PR DESCRIPTION
**Pull request by silentx1981**

### CODE REVIEW

**Comment by jparise** [comment]
What's the reason for this change? The check you added no longer respects the contents of PHP's `include_path`.

**Comment by silentx1981** [comment]
Um 28.04.2016 15:53:39 wurde folgender Fehler registriert: 

Meldung: include_once(): Failed opening 'Auth/SASL.php' for inclusion (include_path='/data/www/.../vendor/pear/pear_exception:/data/www/.../vendor/pear/console_getopt:/data/www/.../vendor/pear/net_socket:/data/www/.../vendor/pear/mail:/data/www/.../vendor/pear/net_smtp:/data/www/...//vendor/pear/mail_mime:/data/www/.../vendor/pear/pear-core-minimal/src:.:')
File: /data/www/.../vendor/pear/net_smtp/Net/SMTP.php
Line: 174

**Comment by jparise** [comment]
The problem with using `file_exists` here is that it won't honor PHP's `include_path`, and that's a requirement for finding `Auth/SASL.php`.

Second, I don't understand why the existing `@` symbol suppressing the `include_once` warning in the first place. That's why it's there.

**Comment by jparise** [comment]
I'm going to close this pending more detail.

**Pull request closed without merging**
