### PR TITLE
Drop PHP4 support + various CS fixes

### PR DESCRIPTION
**Pull request by alecpl**
I'm aware of Net_SMTP2 package existence. However, I'd like to have something PHP7-compatible that does not use exceptions.

### CODE REVIEW

**Comment by jparise** [comment]
This looks pretty good to me.  I'll try to look it over in more detail soon.  My biggest concern is making sure all of the package metadata correctly specifies that this is a major new release with a minimum PHP 5 requirement and an updated API version.

**Comment by jparise** [comment]
@alecpl, would you mind resolving the merge conflict?

**Comment by alecpl** [comment]
Done.

**Comment by jparise** [comment]
Thanks so much! I squashed your commits and merged this into master as 0b44891a6370f3ff7eb494135cd4fa85ddd840f3.  This marks the start of the Net_SMTP 2.x line that requires PHP 5+.

**Pull request closed without merging**
